### ISSUE TITLE
User Testing Feedback WT22/23

### ISSUE THREAD

**Issue by Clashsoft** [fujaba/fulib.org#286]
Please collect comments, feedback, opinions here.

Template:

```
# 2022-XX-XX, XX Assignment X

## General

## Feature Requests

## Improvement Suggestions

## Bugs
```

**Comment by nataschu** [comment]
# 2022-11-02, EidI Assignment 02
## Improvement Suggestion
Make text area resizable in Edit Assignment > Tasks > Markdown:

![image](https://user-images.githubusercontent.com/23423613/199445264-11ff05ac-5e3a-4a67-88cd-8e0f214bc084.png)

**Comment by ClemensEmme** [comment]
# 2022-11-07, EidI Assignment 02

## Bugs
Strange hit count 

![image](https://user-images.githubusercontent.com/23365596/200272646-17c94921-c1d7-4042-a869-bf39c51117c7.png)

**Comment by nataschu** [comment]
# 2022-11-07, EidI Assignment 2

## Improvement Suggestions

Toast should be visible also when you scrolled down

![image](https://user-images.githubusercontent.com/23423613/200346585-ea0734dd-5485-4da5-8efa-55a9425b087f.png)

**Comment by Morphclue** [comment]
# 2022-11-14, PM Assignment 2
## Improvement Suggestions
It would be great if I could see remarked correction notes somehow e.g.
- Did not do X 👤📑
- Did not do Y 👤

Hovering over the 📑could display the remark.

**Comment by Morphclue** [comment]
# 2022-11-14, PM Assignment 2
## Improvement Suggestions
Pressing `back` inside an assignment where you have added a remark previously opens up the evaluation-modal instead of sending me back to the assignment list.

**Comment by Morphclue** [comment]
# 2022-11-14, PM Assignment 2
## Feature Requests
* "Submit all issues"-button instead of clicking them one by one

## Improvement Suggestions
Is there any reason why we are still working with an Excel-spreadsheet in addition to Fulib?
Because currently I always have to take my name from the spreadsheet and then transfer the points I submitted on Fulib back into the spreadsheet. Wouldn't it make more sense that (a) Fulib has the possibility to enter correctors automatically and (b) everything takes place on Fulib? I mean you could still generate a spreadsheet at the end when all assignments are done.

**Comment by Morphclue** [comment]
# 2022-11-21, PM Assignment 3

## Improvement Suggestions
* Highlight syntax in `Code Search` Tab, when comparing snippets.

**Comment by Morphclue** [comment]
# 2022-08-12, PM Assignment 4
## Improvement Suggestions

- [ ] It would be super useful if fulib.org and vscode checks the commit-id, because it's very easy to forget. Although you see it immediately when you see incorrectly highlighted lines of code, an automatic check and subsequent warning would be more useful imo.

- [ ] Also, I think the tooltip is only displayed when hovering over the text. It might make more sense to put it one higher in the hierarchy (i.e. on the box around the text). If you move your mouse a little bit out of the text and back on it, no tooltip appears anymore (see screenshot).

![image](https://user-images.githubusercontent.com/43741877/206386742-f61e72a6-5b5f-47c4-aff1-1238cc56f345.png)

**Comment by Clashsoft** [comment]
# 2022-12-08, PM Assignment 4

## Feature Requests

* When automatic Classroom import fails, there is no webhook notification. 
* In addition, an automatic check if import is possible, perhaps some hours in advance, could be useful.

**Comment by Morphclue** [comment]
# 2022-12-12, PM Assignment 5
## Improvement Suggestions
![image](https://user-images.githubusercontent.com/43741877/207054431-1405659b-70d7-4b88-9bfd-1282cafa2b0f.png)
Clicking on a statistic description isn't very readable.

**Comment by Morphclue** [comment]
# 2022-12-12, PM Assignment 5
## Improvement Suggestions
![image](https://user-images.githubusercontent.com/43741877/207380616-ecb67a83-fae4-4bfb-b90c-c6029a5be14e.png)

Maybe I'm using the system wrong here (apart from the -3P, which was habitual and clarified in Discord), but: I find it strange that when you have a top point and the points are automatically added up, that the same minus points in a top category lead to different suggestions (thanks to the manual addition). This is of course totally logical in the current system and it can be fixed by introducing another subitem. But shouldn't this be feasible in a different way?
